### ISSUE TITLE
Banner - Responsive Checking : Banner images are clipped. What are seen from desktop view should also be in seen in different resolution.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#107]
![108](https://cloud.githubusercontent.com/assets/18256652/16029179/4b15341a-3219-11e6-8c1f-c9ef1dc33fc7.png)

**Comment by zackneron** [comment]
To prevent distortion of the image, doing this wouldn't be possible.
Can shift image to show more of the right side, but can't present same image at scale of desktop.
