### ISSUE TITLE
Homepage-Content : Text content should have limit and there should be a "Reveal More" button to show the rest of the text. Please follow the psd design on the number of line limit.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#13]
![13](https://cloud.githubusercontent.com/assets/18256652/15640711/6fce5b36-266d-11e6-853c-55f032c02106.png)

**Comment by bukssaayman** [comment]
Fixed.

**Comment by iteano** [comment]
Not Fixed.

**Comment by bukssaayman** [comment]
I offer my sincerest apologies. Gulp was removing my js file placed in the js folder. I moved it to a different folder. Everything works now.
