### ISSUE TITLE
Gallery : No pagination.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#132]
![133](https://cloud.githubusercontent.com/assets/18256652/16145849/7e6b6168-34ad-11e6-9bdf-b390d095fe58.png)

**Comment by bukssaayman** [comment]
Not a bug. in wp-admin under titan theme options --> Gallery Image Pagination, it was set to paginate at 30 images. If you test pagination and increase/decrease the amount, please set it back to what it was, or should be.
