### ISSUE TITLE
Gallery - Close button should not overlaps with the image.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#142]
![143](https://cloud.githubusercontent.com/assets/18256652/16186680/633d8918-36fe-11e6-8dc4-843e36430f7d.png)

**Comment by iteano** [comment]
Apply back the close button, please see attached screenshot for reference.

![Uploading 150.png…]()

**Comment by bukssaayman** [comment]
close button added.
