### ISSUE TITLE
General - Seems that all images are stretched which makes it not presentable. Please refer to the site link given, to see how the images been managed even in different resolution.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#153]
Note : Try to switch on different viewport size and observe how the image changes without being pixelated and stretched.

http://roarfitness247.stage.titanweb.com.au/blog/

**Comment by iteano** [comment]
Images still stretch even in desktop view. Please see images on these following pages.
1. Services Single
2. Project
3. Project Single
4. Blog
5. Blog Single

Thanks.

**Comment by bukssaayman** [comment]
Service Single is correct. The images do not stretch, look at my attached document.
Project has been fixed, it was incorrect.
Project Single has been fixed, it was incorrect.
Blog has been fixed, it was incorrect.
Blog 
[service singe.pdf](https://github.com/titan-cebu/Quality-Traffic-Management/files/331223/service.singe.pdf)
Single has been fixed, it was incorrect.
