### ISSUE TITLE
Project Single : Fancy box image doesn't have design.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#154]
![156](https://cloud.githubusercontent.com/assets/18256652/16325117/a91a9fce-39ed-11e6-910a-cf900f01abc7.png)

**Comment by bukssaayman** [comment]
I'm not 100% sure what is meant by the bug description "Fancy box image doesn't have design". I have changed that lighbox from a thickbox to fancybox to fit in with the gallery page.

**Comment by iteano** [comment]
Please follow the fancybox design from the gallery page. See attached for reference.

![158](https://cloud.githubusercontent.com/assets/18256652/16331231/757864ba-3a21-11e6-85f0-778278c883c6.png)

**Comment by bukssaayman** [comment]
It was a source control issue that caused my changes to be overwritten. I just re-applied them and this is working now.
