### ISSUE TITLE
GENERAL : Text used instead of a defualt image placeholder when no featured image set.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#19]
![19](https://cloud.githubusercontent.com/assets/18256652/15641412/430441c8-2673-11e6-9618-f18544055919.png)

**Comment by bukssaayman** [comment]
Fixed. If no image uploaded, we will use the default image.

**Comment by iteano** [comment]
Reopening this ticket, issue occurs during cleanup on Blog page.
![159](https://cloud.githubusercontent.com/assets/18256652/16332214/76981ad8-3a27-11e6-866e-35923e080200.png)

**Comment by iteano** [comment]
This was already fixed before but came back this time, occurs also on Services single.

![160](https://cloud.githubusercontent.com/assets/18256652/16332352/11822c28-3a28-11e6-8e46-8c59cf9f65e9.png)

**Comment by bukssaayman** [comment]
Apologies for that. It's fixed now.
