### ISSUE TITLE
GENERAL - "Read More" button is not dynamic. It should be hidden on the frontend if value is not set, or changes should reflect if set from the backend.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#20]
![20](https://cloud.githubusercontent.com/assets/18256652/15641790/c4dec338-2675-11e6-86c2-861cf5607621.png)

**Comment by bukssaayman** [comment]
That specific read more label has no effect on the read more button on the banner. The read more button for the banner is managed with the banners under the options on the front page.
