### ISSUE TITLE
Admin-General Settings : Incorrect email address used.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#30]
![30](https://cloud.githubusercontent.com/assets/18256652/15645414/d45f93e0-268a-11e6-81d2-38c6197b32cb.png)

**Comment by bukssaayman** [comment]
We will change this e-mail address prior to going live. Whilst we are still fixing QA bugs, there is no point in changing this to the client's e-mail address, because if we need to test forms, it will be sent to the client instead of the developers.
