### ISSUE TITLE
Header Menu : Missing gallery menu.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#41]
![41](https://cloud.githubusercontent.com/assets/18256652/15695711/a31b5fe6-27dc-11e6-83cd-0336f64a6111.png)

**Comment by bukssaayman** [comment]
Fixed. It was just deleted form the menu, I've re-added it.

**Comment by iteano** [comment]
Reopening this report. This was already fixed but it exist again.
