### ISSUE TITLE
General : Inconsistent line space for heading at the frontend while no line space set at the backend.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#45]
![45](https://cloud.githubusercontent.com/assets/18256652/15696088/e85cfb66-27df-11e6-969a-1c99388e0bbb.png)

**Comment by zackneron** [comment]
No headings were defined to be used below the content for the About Us page from the design .

**Comment by iteano** [comment]
This is for future use, what if the client will update its about us content.
