### ISSUE TITLE
Banner : Banner should be custom post not an ACF as per scope.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#49]
![49](https://cloud.githubusercontent.com/assets/18256652/15697174/43f3fd9e-27ea-11e6-9903-9362ad9b2034.png)

**Comment by bukssaayman** [comment]
I realize the scope doc requests it to be built as a Custom Post type, but we ran into issues and I can't remember the exact problem but we settled on using ACF repeater. Please can we leave this as is.

**Comment by iteano** [comment]
Okay we just leave this as is but first the scope needs to be updated. Please update the scope with this changes. Thanks.

**Comment by bukssaayman** [comment]
Done. Scope doc updated.
