### ISSUE TITLE
Homepage-Resolution Test : At 767px, social media disappears.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#50]
![50](https://cloud.githubusercontent.com/assets/18256652/15697214/bb13ca12-27ea-11e6-9e84-5b5c33cdafba.png)

**Comment by zackneron** [comment]
Social media icons are hidden from 767px according to the design.

**Comment by iteano** [comment]
Yah, social media hidden as per design. But please just fix the position of the email and phone icon.
![50a](https://cloud.githubusercontent.com/assets/18256652/15887455/f6257e0c-2d94-11e6-8abf-37bd38653302.png)

**Comment by zackneron** [comment]
This was the best option we found to solve this design issue.

**Comment by iteano** [comment]
Reopening this issue please refer to this standard.

https://knowledgebase.titanweb.com.au/implementation/mobile-and-browsers/mobile-desktop-sections
