### ISSUE TITLE
Sitemap : No sitemap page, please implement as required.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#62]
https://knowledgebase.titanweb.com.au/implementation/standard-pages/sitemap-page
![62](https://cloud.githubusercontent.com/assets/18256652/15699894/26bc17f2-2803-11e6-8da9-9a10bd1379e9.png)

**Comment by bukssaayman** [comment]
Fixed. Sitemap created and added.
