### ISSUE TITLE
About Us-W3C : 2 errors and a warning on the page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#64]
![64](https://cloud.githubusercontent.com/assets/18256652/15700172/013b5bf8-2805-11e6-9ed3-3d2623e3a0a2.png)

**Comment by iteano** [comment]
Still not fixed.

![64a](https://cloud.githubusercontent.com/assets/18256652/15886207/45bbfe70-2d8e-11e6-96ac-ba0874a5332b.png)

**Comment by bukssaayman** [comment]
Fixed now.
