### ISSUE TITLE
Service Singles-W3C : 3 errors and 1 warning on page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#67]
![67](https://cloud.githubusercontent.com/assets/18256652/15700499/b163cbae-2806-11e6-9a58-e15fa031a9a3.png)

**Comment by iteano** [comment]
Still not fixed. New error exist.
![67a](https://cloud.githubusercontent.com/assets/18256652/15885965/ebe583ea-2d8c-11e6-879e-2f518bc66572.png)

**Comment by bukssaayman** [comment]
Should be fixed now.
