### ISSUE TITLE
Projects-W3C : Error on page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#68]
![68](https://cloud.githubusercontent.com/assets/18256652/15700528/ffdb5662-2806-11e6-8ad6-141d8b6cf4c9.png)

**Comment by iteano** [comment]
Still not fixed. Another error exist.

![68a](https://cloud.githubusercontent.com/assets/18256652/15885872/8445b246-2d8c-11e6-9eef-18c03c19042e.png)

**Comment by bukssaayman** [comment]
The is an illegal character in the filename of the uploaded image. Nothing development can do about it. rename the image and re-upload it if it is a big issue. Otherwise, please ignore.
