### ISSUE TITLE
Projects Singles-W3C : Error on page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#69]
![69](https://cloud.githubusercontent.com/assets/18256652/15700581/3fbe2124-2807-11e6-83f6-de81adc5cb70.png)

**Comment by iteano** [comment]
Still have p element error.
![69a](https://cloud.githubusercontent.com/assets/18256652/15885744/d1899898-2d8b-11e6-8108-8a60ed7894e9.png)

**Comment by bukssaayman** [comment]
Fixed.
