### ISSUE TITLE
Blog Singles-W3C : Multiple error on page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#72]
![72](https://cloud.githubusercontent.com/assets/18256652/15700744/7d45f4da-2808-11e6-8c82-fb3d78b0b8a6.png)

**Comment by bukssaayman** [comment]
Item 1 - 22 is for a table inserted with the WYSIWYG editor. Nothing I can do to fix.
Item 23 - 24 is a duplicate button used for mobile responsiveness. The element is duplicated but hidden and displayed when a certain screen resolution comes into play.
