### ISSUE TITLE
Contact Us-W3C : Error on page.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#73]
![73](https://cloud.githubusercontent.com/assets/18256652/15700775/b5f9fb78-2808-11e6-8367-351bd32d6367.png)

**Comment by zackneron** [comment]
Error 1 -2 Duplicate ID were used for responsiveness for different break point views.
Error 3 Buks will remove the space within the tel link
Error 4 - 5 Fixed
