### ISSUE TITLE
General Form : No field title text on the email notification.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#74]
![74](https://cloud.githubusercontent.com/assets/18256652/15701285/d7310428-280b-11e6-9b47-2ddfb1e0e163.png)

**Comment by bukssaayman** [comment]
I've had to add labels for the Gravity form. I'll ask Zack to hide the labels on the front-end.

**Comment by iteano** [comment]
Still not fixed on Enquire now form.

![74a](https://cloud.githubusercontent.com/assets/18256652/15885566/a0031700-2d8a-11e6-8e94-ad0b98d8af51.png)

**Comment by bukssaayman** [comment]
Fixed on enquire form now too.
