### ISSUE TITLE
Homepage - Leadins : Defualt image placeholder are stretched.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#88]
![88](https://cloud.githubusercontent.com/assets/18256652/15916260/60cc85f0-2e23-11e6-8f7d-1c2c37df326e.png)

**Comment by zackneron** [comment]
We set a default width and height as per your first complaint of other images being smaller than others.
When you insert an image lesser than 390/280 it will be stretched.
