### ISSUE TITLE
Homepage - Leadins : Leadin images and featured image of its page linked are out of sync. Images displayed on leadins should be the featured image of its page linked.

### ISSUE THREAD

**Issue by iteano** [titan-cebu/Quality-Traffic-Management#89]
![89](https://cloud.githubusercontent.com/assets/18256652/15916569/b169cccc-2e26-11e6-98a1-c18c0c33ceb5.png)

**Comment by bukssaayman** [comment]
I ran this past Jonathan Marshall who agreed that this is not a QA issue. Those leadins are content managed including the image and do not pull the image form the linked page.
